// Algorithmic career scoring for when AI is opted out.
// Score weights: 3 = strong match, 2 = good match, 1 = partial, 0 = poor fit
// Max per category is always 3 so scores normalize cleanly.

type Weights = Record<string, number>;
type Profile = Record<string, Weights>;

const HEALTHCARE: Record<number, Profile> = {
  1: { // Registered Nurse (RN)
    Education: { minimal: 0, short: 1, medium: 3, long: 2 },
    Motivation: { money: 2, passion: 3, balance: 1, growth: 3 },
    "Patient Interaction": { all_the_time: 3, some: 1, minimal: 0 },
    "Medical Comfort": { very: 3, somewhat: 2, not_really: 0 },
    "Work Environment": { fast: 2, moderate: 3, calm: 1 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 3, clinic: 2, community: 1, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 1, counseling: 1, administrative: 0 },
  },
  2: { // Licensed Vocational Nurse (LVN)
    Education: { minimal: 0, short: 3, medium: 1, long: 0 },
    Motivation: { money: 1, passion: 3, balance: 2, growth: 2 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 2, somewhat: 3, not_really: 0 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 2, adults: 3, elderly: 3, all: 3 },
    "Work Setting": { hospital: 2, clinic: 3, community: 2, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 1, counseling: 1, administrative: 1 },
  },
  3: { // CNA
    Education: { minimal: 3, short: 1, medium: 0, long: 0 },
    Motivation: { money: 0, passion: 3, balance: 2, growth: 1 },
    "Patient Interaction": { all_the_time: 3, some: 1, minimal: 0 },
    "Medical Comfort": { very: 2, somewhat: 3, not_really: 0 },
    "Work Environment": { fast: 0, moderate: 2, calm: 3 },
    Population: { children: 1, adults: 2, elderly: 3, all: 2 },
    "Work Setting": { hospital: 2, clinic: 1, community: 3, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 0, counseling: 1, administrative: 0 },
  },
  4: { // EMT / Paramedic
    Education: { minimal: 3, short: 2, medium: 0, long: 0 },
    Motivation: { money: 1, passion: 2, balance: 0, growth: 3 },
    "Patient Interaction": { all_the_time: 3, some: 1, minimal: 0 },
    "Medical Comfort": { very: 3, somewhat: 1, not_really: 0 },
    "Work Environment": { fast: 3, moderate: 1, calm: 0 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 2, clinic: 0, community: 3, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 1, counseling: 1, administrative: 0 },
  },
  5: { // Medical Assistant
    Education: { minimal: 2, short: 3, medium: 0, long: 0 },
    Motivation: { money: 1, passion: 2, balance: 3, growth: 2 },
    "Patient Interaction": { all_the_time: 2, some: 3, minimal: 1 },
    "Medical Comfort": { very: 2, somewhat: 3, not_really: 0 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 2, adults: 3, elderly: 1, all: 3 },
    "Work Setting": { hospital: 1, clinic: 3, community: 1, office: 1 },
    "Daily Tasks": { hands_on: 2, technology: 1, counseling: 1, administrative: 3 },
  },
  6: { // Phlebotomist
    Education: { minimal: 3, short: 2, medium: 0, long: 0 },
    Motivation: { money: 1, passion: 1, balance: 3, growth: 1 },
    "Patient Interaction": { all_the_time: 2, some: 3, minimal: 1 },
    "Medical Comfort": { very: 3, somewhat: 2, not_really: 0 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 3, clinic: 2, community: 1, office: 1 },
    "Daily Tasks": { hands_on: 3, technology: 2, counseling: 0, administrative: 0 },
  },
  7: { // Pharmacy Technician
    Education: { minimal: 2, short: 3, medium: 0, long: 0 },
    Motivation: { money: 1, passion: 1, balance: 3, growth: 1 },
    "Patient Interaction": { all_the_time: 1, some: 3, minimal: 2 },
    "Medical Comfort": { very: 1, somewhat: 3, not_really: 2 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 1, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 2, clinic: 3, community: 0, office: 1 },
    "Daily Tasks": { hands_on: 1, technology: 2, counseling: 0, administrative: 3 },
  },
  8: { // Dental Assistant
    Education: { minimal: 2, short: 3, medium: 0, long: 0 },
    Motivation: { money: 1, passion: 2, balance: 3, growth: 1 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 2, somewhat: 3, not_really: 0 },
    "Work Environment": { fast: 0, moderate: 3, calm: 2 },
    Population: { children: 2, adults: 3, elderly: 1, all: 3 },
    "Work Setting": { hospital: 0, clinic: 3, community: 1, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 1, counseling: 1, administrative: 2 },
  },
  9: { // Home Health Aide
    Education: { minimal: 3, short: 1, medium: 0, long: 0 },
    Motivation: { money: 0, passion: 3, balance: 2, growth: 0 },
    "Patient Interaction": { all_the_time: 3, some: 1, minimal: 0 },
    "Medical Comfort": { very: 2, somewhat: 3, not_really: 1 },
    "Work Environment": { fast: 0, moderate: 2, calm: 3 },
    Population: { children: 1, adults: 2, elderly: 3, all: 2 },
    "Work Setting": { hospital: 0, clinic: 0, community: 3, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 0, counseling: 1, administrative: 0 },
  },
  10: { // Medical Biller / Coding Specialist
    Education: { minimal: 2, short: 3, medium: 0, long: 0 },
    Motivation: { money: 2, passion: 0, balance: 3, growth: 1 },
    "Patient Interaction": { all_the_time: 0, some: 1, minimal: 3 },
    "Medical Comfort": { very: 1, somewhat: 2, not_really: 3 },
    "Work Environment": { fast: 0, moderate: 2, calm: 3 },
    Population: { children: 0, adults: 1, elderly: 0, all: 2 },
    "Work Setting": { hospital: 2, clinic: 2, community: 0, office: 3 },
    "Daily Tasks": { hands_on: 0, technology: 2, counseling: 0, administrative: 3 },
  },
  11: { // Health Information Technologist
    Education: { minimal: 1, short: 3, medium: 1, long: 0 },
    Motivation: { money: 2, passion: 0, balance: 3, growth: 2 },
    "Patient Interaction": { all_the_time: 0, some: 1, minimal: 3 },
    "Medical Comfort": { very: 1, somewhat: 2, not_really: 3 },
    "Work Environment": { fast: 1, moderate: 2, calm: 3 },
    Population: { children: 0, adults: 1, elderly: 0, all: 2 },
    "Work Setting": { hospital: 2, clinic: 2, community: 0, office: 3 },
    "Daily Tasks": { hands_on: 0, technology: 3, counseling: 0, administrative: 3 },
  },
  12: { // Dental Hygienist
    Education: { minimal: 0, short: 1, medium: 3, long: 0 },
    Motivation: { money: 3, passion: 2, balance: 3, growth: 1 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 2, somewhat: 3, not_really: 0 },
    "Work Environment": { fast: 0, moderate: 3, calm: 2 },
    Population: { children: 2, adults: 3, elderly: 1, all: 3 },
    "Work Setting": { hospital: 0, clinic: 3, community: 1, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 1, counseling: 1, administrative: 1 },
  },
  13: { // Respiratory Therapist
    Education: { minimal: 0, short: 2, medium: 3, long: 0 },
    Motivation: { money: 2, passion: 2, balance: 2, growth: 2 },
    "Patient Interaction": { all_the_time: 2, some: 3, minimal: 0 },
    "Medical Comfort": { very: 3, somewhat: 2, not_really: 0 },
    "Work Environment": { fast: 2, moderate: 3, calm: 1 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 3, clinic: 1, community: 1, office: 0 },
    "Daily Tasks": { hands_on: 2, technology: 3, counseling: 1, administrative: 0 },
  },
  14: { // Radiologic Technologist
    Education: { minimal: 0, short: 2, medium: 3, long: 0 },
    Motivation: { money: 2, passion: 1, balance: 2, growth: 2 },
    "Patient Interaction": { all_the_time: 1, some: 3, minimal: 1 },
    "Medical Comfort": { very: 3, somewhat: 2, not_really: 0 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 3, clinic: 2, community: 0, office: 1 },
    "Daily Tasks": { hands_on: 1, technology: 3, counseling: 0, administrative: 1 },
  },
  15: { // Surgical Technician
    Education: { minimal: 0, short: 3, medium: 1, long: 0 },
    Motivation: { money: 2, passion: 2, balance: 1, growth: 2 },
    "Patient Interaction": { all_the_time: 2, some: 2, minimal: 1 },
    "Medical Comfort": { very: 3, somewhat: 1, not_really: 0 },
    "Work Environment": { fast: 3, moderate: 2, calm: 0 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 3, clinic: 1, community: 0, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 2, counseling: 0, administrative: 0 },
  },
  16: { // Physical Therapist Assistant
    Education: { minimal: 0, short: 2, medium: 3, long: 0 },
    Motivation: { money: 1, passion: 3, balance: 2, growth: 2 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 2, somewhat: 3, not_really: 0 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 2, adults: 3, elderly: 3, all: 3 },
    "Work Setting": { hospital: 2, clinic: 3, community: 2, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 1, counseling: 1, administrative: 0 },
  },
  17: { // Diagnostic Technician (Ultrasound)
    Education: { minimal: 0, short: 1, medium: 3, long: 0 },
    Motivation: { money: 3, passion: 1, balance: 2, growth: 2 },
    "Patient Interaction": { all_the_time: 1, some: 3, minimal: 1 },
    "Medical Comfort": { very: 2, somewhat: 3, not_really: 0 },
    "Work Environment": { fast: 0, moderate: 3, calm: 2 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 3, clinic: 2, community: 0, office: 1 },
    "Daily Tasks": { hands_on: 1, technology: 3, counseling: 0, administrative: 0 },
  },
  18: { // Patient Representative / Health Navigator
    Education: { minimal: 1, short: 3, medium: 1, long: 0 },
    Motivation: { money: 0, passion: 3, balance: 2, growth: 1 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 1, somewhat: 2, not_really: 3 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 2, adults: 3, elderly: 3, all: 3 },
    "Work Setting": { hospital: 2, clinic: 2, community: 2, office: 2 },
    "Daily Tasks": { hands_on: 0, technology: 1, counseling: 3, administrative: 2 },
  },
  19: { // Community Health Worker
    Education: { minimal: 2, short: 3, medium: 1, long: 0 },
    Motivation: { money: 0, passion: 3, balance: 1, growth: 1 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 1, somewhat: 2, not_really: 3 },
    "Work Environment": { fast: 0, moderate: 2, calm: 3 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 0, clinic: 1, community: 3, office: 1 },
    "Daily Tasks": { hands_on: 0, technology: 0, counseling: 3, administrative: 1 },
  },
  20: { // Health Education Specialist
    Education: { minimal: 0, short: 2, medium: 3, long: 1 },
    Motivation: { money: 1, passion: 3, balance: 2, growth: 2 },
    "Patient Interaction": { all_the_time: 2, some: 3, minimal: 1 },
    "Medical Comfort": { very: 1, somewhat: 2, not_really: 3 },
    "Work Environment": { fast: 0, moderate: 2, calm: 3 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 1, clinic: 1, community: 3, office: 2 },
    "Daily Tasks": { hands_on: 0, technology: 1, counseling: 3, administrative: 2 },
  },
  21: { // Substance Abuse Counselor
    Education: { minimal: 0, short: 2, medium: 3, long: 1 },
    Motivation: { money: 0, passion: 3, balance: 1, growth: 2 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 1, somewhat: 2, not_really: 3 },
    "Work Environment": { fast: 0, moderate: 2, calm: 3 },
    Population: { children: 1, adults: 3, elderly: 1, all: 2 },
    "Work Setting": { hospital: 1, clinic: 2, community: 3, office: 2 },
    "Daily Tasks": { hands_on: 0, technology: 0, counseling: 3, administrative: 1 },
  },
  22: { // Healthcare Administrator
    Education: { minimal: 0, short: 1, medium: 3, long: 2 },
    Motivation: { money: 3, passion: 1, balance: 2, growth: 3 },
    "Patient Interaction": { all_the_time: 0, some: 2, minimal: 3 },
    "Medical Comfort": { very: 1, somewhat: 2, not_really: 3 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 0, adults: 1, elderly: 0, all: 2 },
    "Work Setting": { hospital: 3, clinic: 3, community: 1, office: 3 },
    "Daily Tasks": { hands_on: 0, technology: 2, counseling: 1, administrative: 3 },
  },
  23: { // Clinical Research Coordinator
    Education: { minimal: 0, short: 1, medium: 3, long: 2 },
    Motivation: { money: 2, passion: 2, balance: 2, growth: 3 },
    "Patient Interaction": { all_the_time: 1, some: 3, minimal: 2 },
    "Medical Comfort": { very: 2, somewhat: 3, not_really: 1 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 1, adults: 3, elderly: 1, all: 2 },
    "Work Setting": { hospital: 2, clinic: 2, community: 1, office: 3 },
    "Daily Tasks": { hands_on: 1, technology: 3, counseling: 1, administrative: 3 },
  },
  24: { // Nutritionist / Dietary Aide
    Education: { minimal: 1, short: 2, medium: 3, long: 1 },
    Motivation: { money: 1, passion: 3, balance: 2, growth: 1 },
    "Patient Interaction": { all_the_time: 2, some: 3, minimal: 1 },
    "Medical Comfort": { very: 1, somewhat: 2, not_really: 3 },
    "Work Environment": { fast: 0, moderate: 2, calm: 3 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 2, clinic: 2, community: 2, office: 1 },
    "Daily Tasks": { hands_on: 1, technology: 1, counseling: 3, administrative: 1 },
  },
  25: { // Speech-Language Pathologist
    Education: { minimal: 0, short: 0, medium: 1, long: 3 },
    Motivation: { money: 2, passion: 3, balance: 2, growth: 2 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 1, somewhat: 2, not_really: 2 },
    "Work Environment": { fast: 0, moderate: 2, calm: 3 },
    Population: { children: 3, adults: 2, elderly: 2, all: 3 },
    "Work Setting": { hospital: 2, clinic: 2, community: 2, office: 1 },
    "Daily Tasks": { hands_on: 1, technology: 1, counseling: 3, administrative: 0 },
  },
  26: { // Occupational Therapist
    Education: { minimal: 0, short: 0, medium: 1, long: 3 },
    Motivation: { money: 2, passion: 3, balance: 2, growth: 2 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 2, somewhat: 3, not_really: 0 },
    "Work Environment": { fast: 0, moderate: 3, calm: 2 },
    Population: { children: 3, adults: 3, elderly: 3, all: 3 },
    "Work Setting": { hospital: 2, clinic: 3, community: 2, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 1, counseling: 2, administrative: 0 },
  },
  27: { // Physician Assistant (PA)
    Education: { minimal: 0, short: 0, medium: 1, long: 3 },
    Motivation: { money: 3, passion: 2, balance: 1, growth: 3 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 3, somewhat: 1, not_really: 0 },
    "Work Environment": { fast: 2, moderate: 3, calm: 1 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 2, clinic: 3, community: 1, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 1, counseling: 2, administrative: 0 },
  },
  28: { // Nurse Practitioner (NP)
    Education: { minimal: 0, short: 0, medium: 1, long: 3 },
    Motivation: { money: 3, passion: 3, balance: 1, growth: 3 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 3, somewhat: 2, not_really: 0 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 2, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 2, clinic: 3, community: 2, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 1, counseling: 2, administrative: 0 },
  },
  29: { // Pharmacist
    Education: { minimal: 0, short: 0, medium: 0, long: 3 },
    Motivation: { money: 3, passion: 1, balance: 3, growth: 2 },
    "Patient Interaction": { all_the_time: 1, some: 3, minimal: 2 },
    "Medical Comfort": { very: 2, somewhat: 2, not_really: 1 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 1, adults: 3, elderly: 2, all: 3 },
    "Work Setting": { hospital: 2, clinic: 3, community: 0, office: 2 },
    "Daily Tasks": { hands_on: 1, technology: 2, counseling: 1, administrative: 3 },
  },
  30: { // Physical Therapist (PT)
    Education: { minimal: 0, short: 0, medium: 0, long: 3 },
    Motivation: { money: 3, passion: 3, balance: 2, growth: 2 },
    "Patient Interaction": { all_the_time: 3, some: 2, minimal: 0 },
    "Medical Comfort": { very: 2, somewhat: 3, not_really: 0 },
    "Work Environment": { fast: 1, moderate: 3, calm: 2 },
    Population: { children: 2, adults: 3, elderly: 3, all: 3 },
    "Work Setting": { hospital: 2, clinic: 3, community: 2, office: 0 },
    "Daily Tasks": { hands_on: 3, technology: 1, counseling: 1, administrative: 0 },
  },
};

const EDUCATION: Record<number, Profile> = {
  31: { // K-12 Paraprofessional / Teacher's Aide
    Education: { certificate: 3, associates: 2, bachelors: 1, masters: 0 },
    Motivation: { inspire: 2, community: 2, subject: 1, stability: 3 },
    "Age Group": { early_childhood: 2, elementary: 3, secondary: 3, adult: 0 },
    "Role Type": { classroom: 2, support: 3, specialist: 0, childcare: 1 },
    Environment: { structured: 3, dynamic: 2, flexible: 1 },
    "Focus Area": { teaching: 2, wellbeing: 1, leadership: 0, resources: 1 },
    "Special Needs": { love_it: 2, open: 2, general: 3 },
  },
  32: { // Child Development Assistant
    Education: { certificate: 3, associates: 2, bachelors: 0, masters: 0 },
    Motivation: { inspire: 3, community: 2, subject: 1, stability: 2 },
    "Age Group": { early_childhood: 3, elementary: 1, secondary: 0, adult: 0 },
    "Role Type": { classroom: 1, support: 2, specialist: 0, childcare: 3 },
    Environment: { structured: 2, dynamic: 3, flexible: 2 },
    "Focus Area": { teaching: 2, wellbeing: 2, leadership: 0, resources: 0 },
    "Special Needs": { love_it: 2, open: 2, general: 2 },
  },
  33: { // Bilingual Assistant / Interpreter
    Education: { certificate: 3, associates: 2, bachelors: 1, masters: 0 },
    Motivation: { inspire: 2, community: 3, subject: 1, stability: 2 },
    "Age Group": { early_childhood: 2, elementary: 3, secondary: 3, adult: 2 },
    "Role Type": { classroom: 1, support: 3, specialist: 2, childcare: 1 },
    Environment: { structured: 2, dynamic: 3, flexible: 2 },
    "Focus Area": { teaching: 1, wellbeing: 2, leadership: 0, resources: 1 },
    "Special Needs": { love_it: 2, open: 2, general: 2 },
  },
  34: { // School Bus Driver
    Education: { certificate: 3, associates: 1, bachelors: 0, masters: 0 },
    Motivation: { inspire: 1, community: 2, subject: 0, stability: 3 },
    "Age Group": { early_childhood: 2, elementary: 3, secondary: 3, adult: 0 },
    "Role Type": { classroom: 0, support: 2, specialist: 0, childcare: 0 },
    Environment: { structured: 3, dynamic: 1, flexible: 0 },
    "Focus Area": { teaching: 0, wellbeing: 1, leadership: 0, resources: 0 },
    "Special Needs": { love_it: 1, open: 2, general: 3 },
  },
  35: { // Instructional Assistant
    Education: { certificate: 1, associates: 3, bachelors: 1, masters: 0 },
    Motivation: { inspire: 3, community: 2, subject: 1, stability: 2 },
    "Age Group": { early_childhood: 1, elementary: 3, secondary: 3, adult: 1 },
    "Role Type": { classroom: 2, support: 3, specialist: 1, childcare: 1 },
    Environment: { structured: 3, dynamic: 2, flexible: 1 },
    "Focus Area": { teaching: 3, wellbeing: 1, leadership: 0, resources: 1 },
    "Special Needs": { love_it: 2, open: 3, general: 2 },
  },
  36: { // Special Education Assistant
    Education: { certificate: 1, associates: 3, bachelors: 1, masters: 0 },
    Motivation: { inspire: 3, community: 2, subject: 1, stability: 2 },
    "Age Group": { early_childhood: 2, elementary: 3, secondary: 3, adult: 0 },
    "Role Type": { classroom: 1, support: 3, specialist: 2, childcare: 1 },
    Environment: { structured: 3, dynamic: 2, flexible: 1 },
    "Focus Area": { teaching: 2, wellbeing: 3, leadership: 0, resources: 0 },
    "Special Needs": { love_it: 3, open: 2, general: 0 },
  },
  37: { // Afterschool Site Manager
    Education: { certificate: 1, associates: 3, bachelors: 1, masters: 0 },
    Motivation: { inspire: 2, community: 3, subject: 1, stability: 2 },
    "Age Group": { early_childhood: 1, elementary: 3, secondary: 2, adult: 0 },
    "Role Type": { classroom: 1, support: 2, specialist: 1, childcare: 2 },
    Environment: { structured: 2, dynamic: 3, flexible: 2 },
    "Focus Area": { teaching: 2, wellbeing: 2, leadership: 2, resources: 1 },
    "Special Needs": { love_it: 2, open: 2, general: 2 },
  },
  38: { // Library Technician
    Education: { certificate: 2, associates: 3, bachelors: 1, masters: 0 },
    Motivation: { inspire: 2, community: 2, subject: 3, stability: 2 },
    "Age Group": { early_childhood: 2, elementary: 2, secondary: 2, adult: 2 },
    "Role Type": { classroom: 0, support: 2, specialist: 2, childcare: 0 },
    Environment: { structured: 3, dynamic: 1, flexible: 1 },
    "Focus Area": { teaching: 1, wellbeing: 1, leadership: 0, resources: 3 },
    "Special Needs": { love_it: 1, open: 2, general: 3 },
  },
  39: { // Child Development Teacher
    Education: { certificate: 2, associates: 3, bachelors: 1, masters: 0 },
    Motivation: { inspire: 3, community: 2, subject: 1, stability: 2 },
    "Age Group": { early_childhood: 3, elementary: 1, secondary: 0, adult: 0 },
    "Role Type": { classroom: 2, support: 1, specialist: 0, childcare: 3 },
    Environment: { structured: 2, dynamic: 3, flexible: 2 },
    "Focus Area": { teaching: 3, wellbeing: 2, leadership: 0, resources: 0 },
    "Special Needs": { love_it: 2, open: 2, general: 2 },
  },
  40: { // CTE Instructor
    Education: { certificate: 1, associates: 2, bachelors: 3, masters: 1 },
    Motivation: { inspire: 2, community: 2, subject: 3, stability: 2 },
    "Age Group": { early_childhood: 0, elementary: 0, secondary: 3, adult: 2 },
    "Role Type": { classroom: 3, support: 0, specialist: 1, childcare: 0 },
    Environment: { structured: 2, dynamic: 3, flexible: 1 },
    "Focus Area": { teaching: 3, wellbeing: 0, leadership: 1, resources: 1 },
    "Special Needs": { love_it: 1, open: 2, general: 3 },
  },
  41: { // Substitute Teacher
    Education: { certificate: 0, associates: 0, bachelors: 3, masters: 0 },
    Motivation: { inspire: 2, community: 2, subject: 2, stability: 1 },
    "Age Group": { early_childhood: 1, elementary: 3, secondary: 3, adult: 0 },
    "Role Type": { classroom: 3, support: 1, specialist: 0, childcare: 0 },
    Environment: { structured: 1, dynamic: 3, flexible: 3 },
    "Focus Area": { teaching: 3, wellbeing: 1, leadership: 0, resources: 0 },
    "Special Needs": { love_it: 1, open: 2, general: 3 },
  },
  42: { // Child Development Site Supervisor
    Education: { certificate: 0, associates: 1, bachelors: 3, masters: 1 },
    Motivation: { inspire: 2, community: 2, subject: 1, stability: 2 },
    "Age Group": { early_childhood: 3, elementary: 1, secondary: 0, adult: 0 },
    "Role Type": { classroom: 1, support: 1, specialist: 1, childcare: 3 },
    Environment: { structured: 2, dynamic: 2, flexible: 1 },
    "Focus Area": { teaching: 1, wellbeing: 2, leadership: 3, resources: 1 },
    "Special Needs": { love_it: 2, open: 2, general: 2 },
  },
  43: { // Elementary School Teacher (K-6)
    Education: { certificate: 0, associates: 0, bachelors: 3, masters: 1 },
    Motivation: { inspire: 3, community: 2, subject: 2, stability: 2 },
    "Age Group": { early_childhood: 1, elementary: 3, secondary: 0, adult: 0 },
    "Role Type": { classroom: 3, support: 0, specialist: 0, childcare: 0 },
    Environment: { structured: 2, dynamic: 3, flexible: 1 },
    "Focus Area": { teaching: 3, wellbeing: 1, leadership: 0, resources: 1 },
    "Special Needs": { love_it: 1, open: 2, general: 3 },
  },
  44: { // Middle/High School Teacher (7-12)
    Education: { certificate: 0, associates: 0, bachelors: 3, masters: 1 },
    Motivation: { inspire: 2, community: 2, subject: 3, stability: 2 },
    "Age Group": { early_childhood: 0, elementary: 0, secondary: 3, adult: 1 },
    "Role Type": { classroom: 3, support: 0, specialist: 0, childcare: 0 },
    Environment: { structured: 2, dynamic: 3, flexible: 1 },
    "Focus Area": { teaching: 3, wellbeing: 1, leadership: 0, resources: 1 },
    "Special Needs": { love_it: 1, open: 2, general: 3 },
  },
  45: { // Special Education Teacher
    Education: { certificate: 0, associates: 0, bachelors: 3, masters: 1 },
    Motivation: { inspire: 3, community: 2, subject: 1, stability: 2 },
    "Age Group": { early_childhood: 2, elementary: 3, secondary: 2, adult: 0 },
    "Role Type": { classroom: 2, support: 1, specialist: 3, childcare: 0 },
    Environment: { structured: 3, dynamic: 2, flexible: 1 },
    "Focus Area": { teaching: 2, wellbeing: 3, leadership: 0, resources: 0 },
    "Special Needs": { love_it: 3, open: 1, general: 0 },
  },
  46: { // Reading and Literacy Teacher
    Education: { certificate: 0, associates: 0, bachelors: 3, masters: 1 },
    Motivation: { inspire: 3, community: 2, subject: 3, stability: 2 },
    "Age Group": { early_childhood: 2, elementary: 3, secondary: 1, adult: 0 },
    "Role Type": { classroom: 3, support: 1, specialist: 2, childcare: 0 },
    Environment: { structured: 3, dynamic: 2, flexible: 1 },
    "Focus Area": { teaching: 3, wellbeing: 1, leadership: 0, resources: 2 },
    "Special Needs": { love_it: 2, open: 2, general: 2 },
  },
  47: { // PK-3 Teacher (Age 3 through 3rd Grade)
    Education: { certificate: 0, associates: 0, bachelors: 3, masters: 1 },
    Motivation: { inspire: 3, community: 2, subject: 1, stability: 2 },
    "Age Group": { early_childhood: 3, elementary: 2, secondary: 0, adult: 0 },
    "Role Type": { classroom: 3, support: 0, specialist: 0, childcare: 2 },
    Environment: { structured: 2, dynamic: 3, flexible: 1 },
    "Focus Area": { teaching: 3, wellbeing: 2, leadership: 0, resources: 0 },
    "Special Needs": { love_it: 1, open: 2, general: 3 },
  },
  48: { // School Counselor / Career Advisor
    Education: { certificate: 0, associates: 0, bachelors: 1, masters: 3 },
    Motivation: { inspire: 2, community: 3, subject: 1, stability: 2 },
    "Age Group": { early_childhood: 1, elementary: 2, secondary: 3, adult: 2 },
    "Role Type": { classroom: 0, support: 1, specialist: 3, childcare: 0 },
    Environment: { structured: 2, dynamic: 2, flexible: 2 },
    "Focus Area": { teaching: 0, wellbeing: 3, leadership: 1, resources: 1 },
    "Special Needs": { love_it: 2, open: 2, general: 2 },
  },
  49: { // School Social Worker
    Education: { certificate: 0, associates: 0, bachelors: 0, masters: 3 },
    Motivation: { inspire: 2, community: 3, subject: 0, stability: 2 },
    "Age Group": { early_childhood: 2, elementary: 2, secondary: 3, adult: 1 },
    "Role Type": { classroom: 0, support: 1, specialist: 3, childcare: 0 },
    Environment: { structured: 2, dynamic: 2, flexible: 2 },
    "Focus Area": { teaching: 0, wellbeing: 3, leadership: 1, resources: 1 },
    "Special Needs": { love_it: 3, open: 2, general: 1 },
  },
  50: { // Instructional Coordinator
    Education: { certificate: 0, associates: 0, bachelors: 1, masters: 3 },
    Motivation: { inspire: 2, community: 2, subject: 2, stability: 3 },
    "Age Group": { early_childhood: 1, elementary: 2, secondary: 2, adult: 2 },
    "Role Type": { classroom: 1, support: 1, specialist: 3, childcare: 0 },
    Environment: { structured: 3, dynamic: 1, flexible: 1 },
    "Focus Area": { teaching: 2, wellbeing: 0, leadership: 2, resources: 3 },
    "Special Needs": { love_it: 1, open: 2, general: 2 },
  },
  51: { // K-12 School Psychologist
    Education: { certificate: 0, associates: 0, bachelors: 0, masters: 3 },
    Motivation: { inspire: 2, community: 3, subject: 1, stability: 2 },
    "Age Group": { early_childhood: 2, elementary: 3, secondary: 3, adult: 0 },
    "Role Type": { classroom: 0, support: 1, specialist: 3, childcare: 0 },
    Environment: { structured: 2, dynamic: 2, flexible: 2 },
    "Focus Area": { teaching: 0, wellbeing: 3, leadership: 1, resources: 1 },
    "Special Needs": { love_it: 3, open: 2, general: 1 },
  },
  52: { // Principal / Vice Principal
    Education: { certificate: 0, associates: 0, bachelors: 1, masters: 3 },
    Motivation: { inspire: 2, community: 2, subject: 1, stability: 3 },
    "Age Group": { early_childhood: 1, elementary: 2, secondary: 2, adult: 0 },
    "Role Type": { classroom: 0, support: 0, specialist: 2, childcare: 0 },
    Environment: { structured: 3, dynamic: 2, flexible: 0 },
    "Focus Area": { teaching: 1, wellbeing: 1, leadership: 3, resources: 1 },
    "Special Needs": { love_it: 2, open: 2, general: 2 },
  },
  53: { // Community College Faculty
    Education: { certificate: 0, associates: 0, bachelors: 1, masters: 3 },
    Motivation: { inspire: 3, community: 2, subject: 3, stability: 2 },
    "Age Group": { early_childhood: 0, elementary: 0, secondary: 0, adult: 3 },
    "Role Type": { classroom: 3, support: 0, specialist: 1, childcare: 0 },
    Environment: { structured: 1, dynamic: 2, flexible: 3 },
    "Focus Area": { teaching: 3, wellbeing: 0, leadership: 1, resources: 1 },
    "Special Needs": { love_it: 1, open: 2, general: 3 },
  },
  54: { // Librarian / Media Specialist
    Education: { certificate: 0, associates: 1, bachelors: 1, masters: 3 },
    Motivation: { inspire: 2, community: 2, subject: 3, stability: 3 },
    "Age Group": { early_childhood: 1, elementary: 2, secondary: 2, adult: 2 },
    "Role Type": { classroom: 0, support: 2, specialist: 3, childcare: 0 },
    Environment: { structured: 3, dynamic: 1, flexible: 2 },
    "Focus Area": { teaching: 1, wellbeing: 1, leadership: 0, resources: 3 },
    "Special Needs": { love_it: 1, open: 2, general: 3 },
  },
  55: { // Early Childhood Education Program Director
    Education: { certificate: 0, associates: 0, bachelors: 2, masters: 3 },
    Motivation: { inspire: 2, community: 2, subject: 1, stability: 3 },
    "Age Group": { early_childhood: 3, elementary: 0, secondary: 0, adult: 1 },
    "Role Type": { classroom: 0, support: 0, specialist: 2, childcare: 3 },
    Environment: { structured: 3, dynamic: 1, flexible: 0 },
    "Focus Area": { teaching: 1, wellbeing: 2, leadership: 3, resources: 1 },
    "Special Needs": { love_it: 2, open: 2, general: 2 },
  },
  56: { // Superintendent / Assistant Superintendent
    Education: { certificate: 0, associates: 0, bachelors: 0, masters: 3 },
    Motivation: { inspire: 1, community: 2, subject: 0, stability: 3 },
    "Age Group": { early_childhood: 1, elementary: 1, secondary: 1, adult: 1 },
    "Role Type": { classroom: 0, support: 0, specialist: 1, childcare: 0 },
    Environment: { structured: 3, dynamic: 1, flexible: 0 },
    "Focus Area": { teaching: 0, wellbeing: 0, leadership: 3, resources: 1 },
    "Special Needs": { love_it: 1, open: 2, general: 2 },
  },
};

export interface ScoredCareer {
  id: number;
  matchPercent: number;
}

export function computeScores(
  answers: Record<string, string | string[]>,
  questions: Array<{ id: string; category: string }>,
  careerIds: number[],
  track: "healthcare" | "education"
): ScoredCareer[] {
  const matrix = track === "healthcare" ? HEALTHCARE : EDUCATION;

  // Build a flat map: category → answer value(s)
  const categoryAnswers: Record<string, string[]> = {};
  for (const q of questions) {
    const ans = answers[q.id];
    if (!ans) continue;
    const values = Array.isArray(ans) ? ans : [ans];
    categoryAnswers[q.category] = values;
  }

  const scored: ScoredCareer[] = [];

  for (const id of careerIds) {
    const profile = matrix[id];
    if (!profile) continue;

    let totalScore = 0;
    let maxScore = 0;

    for (const [category, weights] of Object.entries(profile)) {
      const maxCatScore = Math.max(...Object.values(weights));
      maxScore += maxCatScore;

      const userAnswers = categoryAnswers[category] || [];
      let catScore = 0;
      for (const val of userAnswers) {
        catScore = Math.max(catScore, weights[val] ?? 0);
      }
      totalScore += catScore;
    }

    const matchPercent = maxScore > 0 ? Math.round((totalScore / maxScore) * 100) : 0;
    scored.push({ id, matchPercent });
  }

  return scored.sort((a, b) => b.matchPercent - a.matchPercent);
}
